# Generated by Django 5.1 on 2024-08-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
