# Generated by Django 5.1 on 2024-08-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_rental_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
